openapi: 3.0.3
info:
  title: Library API
  version: 1.1.0
  description: STD22057
servers:
  - url: https://library.com
tags:
  - Books
  - Authors
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: releaseDateMin
          description: |
            If  `releaseDateMax` is not provided, `releaseDateMin` is ignored.
            `releaseDateMin` can not be after `releaseDateMax`.
          schema:
            type: string
            format: date
          required: false
        - $ref: '#/components/schemas/Pagination'

      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
        400:
          description: Request invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response400'
        500:
          description: sever error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response500'
        403:
          description: Request invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response403'
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or update Books
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
        400:
          description: Request invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
  /authors:
    get:
      summary: Get all authors
      operationId: getAuthors
      tags:
        - Authors
      parameters:
        - name: authorName
          in: query
          description: |
            Filter returned authors by given name. 
            If not provided, then list is not filtered.
          schema:
            type: string
          required: false
        - $ref: '#/components/schemas/Pagination'


      responses:
        200:
          description: The list of filtered authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    put:
      summary: Create or update authors
      operationId: crupdateAuthors
      tags:
        - Authors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
  /authors/{aId}:
    delete:
      summary: Delete an author
      operationId: deleteAuthor
      tags:
        - Authors
      parameters:
        - name: aId
          in: path
          description: Author identifier to be deleted
          schema:
            type: string
          required: true
      responses:
        200:
          description: The author deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
  /books/{bookId}/authors/{authorId}:
    put:
      summary: modify the author of a Book by specifying each of their identifiers (ID) separately.
      operationId: update author
      parameters:
        - in: path
        - name: bookId
        - required: false
        - schema:
            type: integer
        - in: path
        - name: authorId
        - required: false
        - schema:
            type: integer
      responses:
          200:
            description: author updated successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Book'
          400:
            description: invalid request
  /books/authors:
    put:
      operationId: updateBooksAuthors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateBookAuthor'
      responses:
        200:
          description: all author updated successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        400:
          description: invalid request
  /authors/import:
    post:
      operationId: importAuthors
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/ImportAuthor'
                - type: file
                  format: application/vnd.ms-excel
  /Book/import:
    post:
      operationId: importAuthors
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/ImportBook'
                - type: file
                  format: application/vnd.ms-excel
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    Author:
      type: object
      properties:
        id:
          type: string
        authorName:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
    Sex:
      type: string
      enum:
        - M
        - F

    CrupdateBook:
      allOf:
        - $ref: '#/components/schemas/Book'
        - type: string
      properties:
        author:
          type: object
          required: false
    UpdateBookAuthor:
      type: object
      properties:
          bookId:
            type: integer
          authorId:
            type: integer
    Pagination:
      type: object
      properties:
        Page:
          type: integer
          default: 1
        Pagesize:
          type: integer
          default: 50
    Response:
      type: object
      properties:
        status:
          type: integer
          properties:
            code:
              type: integer
            message:
              type: string
        body:
          type: any
    Response200:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              type: any
    Response400:
        allOf:
          - $ref: '#/components/schemas/Response'
          - type: object
            properties:
              error:
                type: string
                enum:
                  - "Bad Request"
                  - "Invalid Request"

    Response403:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            error:
              type: string
              enum:
                - "Access denied"
                - "Not allow to do this action"
    Response500:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            error:
              type: string
              enum:
                - "Eternal server error"
                - "An error occurred while processing your request"
  parameters:
    queryPagination:
       in: query
       name: pagination
       schema:
         $ref: '#/components/schemas/Pagination'
    pathPagination:
      in: path
      name: pagination
      schema:
        $ref: '#/components/schemas/Pagination'